In [22]:
import pandas as pd

df = pd.read_csv("../data/sample/procurement_raw_sample.csv")

df.groupby("status")[[
    "budget_fcfa",
    "award_amount_fcfa"
]].count()

              budget_fcfa  award_amount_fcfa
status
Awarded                63                 63
Cancelled              62                  0
Programming            52                  0
Published              60                  0
Unsuccessful           73                  0

In [24]:
import pandas as pd
df = pd.read_csv(
    "../data/sample/procurement_raw_sample.csv"
)
df.head()

,project_id,organization,region,procurement_type,budget_fcfa,status,publication_date,award_amount_fcfa,contractor,processing_days
0,PRJ-0001,MINADER,Littoral,Works,136475314,Awarded,2025-08-17,1.256858e+08,Central Works SARL,40
1,PRJ-0002,MINADER,South,Works,231517555,Unsuccessful,2025-02-02,NaN,NaN,12
2,PRJ-0003,MINMAP,South-West,Works,328206344,Unsuccessful,2025-01-28,NaN,NaN,148
3,PRJ-0004,MINEPAT,South,Supplies,246167269,Published,2026-08-27,NaN,NaN,76
4,PRJ-0005,MINPOSTEL,Centre,Works,187670606,Cancelled,NaN,NaN,NaN,44

In [26]:
df.shape

(310, 10)

In [28]:
df.columns

Index(['project_id', 'organization', 'region', 'procurement_type',
       'budget_fcfa', 'status', 'publication_date', 'award_amount_fcfa',
       'contractor', 'processing_days'],
      dtype='object')

In [30]:
df.dtypes

project_id            object
organization          object
region                object
procurement_type      object
budget_fcfa            int64
status                object
publication_date      object
award_amount_fcfa    float64
contractor            object
processing_days        int64
dtype: object

In [32]:
df.isnull().sum()

project_id             0
organization           8
region                 6
procurement_type       0
budget_fcfa            0
status                 0
publication_date      86
award_amount_fcfa    247
contractor           252
processing_days        0
dtype: int64

In [34]:
(df == "").sum()

project_id           0
organization         0
region               0
procurement_type     0
budget_fcfa          0
status               0
publication_date     0
award_amount_fcfa    0
contractor           0
processing_days      0
dtype: int64

In [36]:
df.duplicated().sum()

10

In [38]:
df.describe()

        budget_fcfa  award_amount_fcfa  processing_days
count  3.100000e+02       6.300000e+01       310.000000
mean   2.535742e+08       2.330731e+08        88.606452
std    1.371793e+08       1.333537e+08        52.053059
min    1.179257e+07       8.628171e+06       -10.000000
25%    1.484372e+08       1.067225e+08        42.250000
50%    2.461968e+08       2.427351e+08        84.500000
75%    3.711339e+08       3.469005e+08       136.000000
max    4.995615e+08       4.654209e+08       180.000000

In [40]:
df["region"].unique()

array(['Littoral', 'South', 'South-West', 'Centre', 'North', 'Far-North',
       nan, 'North-West', 'East', 'West', 'Adamawa', 'North West'],
      dtype=object)

In [42]:
suspicious_awards = df[
    df["award_amount_fcfa"] > df["budget_fcfa"]
]


# Display the suspicious records.
suspicious_awards

,project_id,organization,region,procurement_type,budget_fcfa,status,publication_date,award_amount_fcfa,contractor,processing_days
68,PRJ-0069,MINTP,North-West,Services,25539176,Awarded,2025-04-22,38308764.0,Central Works SARL,157
130,PRJ-0131,MINPOSTEL,East,Supplies,310280620,Awarded,2026-09-28,465420930.0,Central Works SARL,20
157,PRJ-0158,MINSANTE,South,Supplies,183477341,Awarded,2026-07-20,275216011.5,Tech Solutions Cameroon,144
170,PRJ-0171,MINEPAT,Adamawa,Services,251730032,Awarded,2025-09-19,377595048.0,Global Services Ltd,175
225,PRJ-0226,MINEPAT,South,Works,235808125,Awarded,2025-04-24,353712187.5,Mountain Engineering,77